service: jwt-lambda-authoriser

frameworkVersion: '2'

useDotenv: true
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post
          authorizer: auth
  auth:
    handler: auth.handler
    environment:
      TOKEN_ISSUER: ${env:TOKEN_ISSUER, ""}
      AUDIENCE: ${env:AUDIENCE, ""}
      JWKS_URI: ${env:JWKS_URI}
